### ISSUE TITLE
bpt_if: enable Python 3 support

### ISSUE THREAD

**Issue by yegorich** [MrKevinWeiss/Testing#8]
```
Traceback (most recent call last):
  File "bpt_if_test.py", line 19, in <module>
    bpt.execute_changes()
  File "/usr/local/src/Testing/bpt_interface/base_if.py", line 130, in execute_changes
    return self.send_cmd(self.__EXECUTE_CMD)
  File "/usr/local/src/Testing/bpt_interface/base_if.py", line 46, in send_cmd
    self.__dev.write(send_cmd + '\n')
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 518, in write
    d = to_bytes(data)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: 'ex\n'
```

**Comment by MrKevinWeiss** [comment]
Hmmm, ya I should switch to python 3, nice catch!

**Comment by MrKevinWeiss** [comment]
I think I fixed it, I will test with both python 3 and 2 now, Thanks.
